---
title: "Miscallaenous Analyses"
---

Summary: Some brief and models — sensitivity to birth cohorts, compare results for exact sibs vs. those found allowing for some flexibility with byear, etc etc.  

## Setup 
```{r}
## library packages
library(data.table)
library(tidyverse)
library(stargazer)
library(broom)

siblings <- fread("../data/analysis_file.csv")
```


## Exact Sibs match
```{r}
exact_sibs <- siblings %>% 
  filter(byear %in% 1915:1925)  %>% 
  filter(!is.na(bni_std)) %>% 
  filter(fname_std_freq > 500) %>% 
  filter(exact_match == 1) %>% 
  group_by(family) %>%  
  filter(n() %in% 2:5)
 
additional_sibs <- siblings %>% 
  filter(byear %in% 1915:1925)  %>% 
  filter(!is.na(bni_std)) %>% 
  filter(fname_std_freq > 500) %>% 
  filter(exact_match == 0) %>% 
  group_by(family) %>%  
  filter(n() %in% 2:5) 

all_sibs <- siblings %>% 
  filter(byear %in% 1915:1925)  %>% 
  filter(!is.na(bni_std)) %>% 
  filter(fname_std_freq > 500) %>% 
  group_by(family) %>% 
  filter(n() %in% 2:5) 
```


```{r}
bni.add.sibs = felm(death_age ~ bni_std | family + birth_order + byear,  data = additional_sibs)
bni.exact.sibs = felm(death_age ~ bni_std | family + birth_order + byear,  data = exact_sibs2)
bni.all.sibs = felm(death_age ~ bni_std | family + birth_order + byear,  data = all_sibs)

stargazer(bni.exact.sibs, bni.add.sibs, bni.all.sibs, type = "text", object.names = T)
```


```{r}
results <- list()
start_year <- 1900:1920

for (year in start_year) {

sibs <- siblings %>% 
  filter(fname_std_freq > 500) %>% 
  filter(!is.na(bni_std)) %>% 
  filter(byear %in% c(year:(year+10)))  %>% 
  group_by(family) %>% 
  filter(n() %in% 2:5) 

bni.all.sibs = felm(death_age ~ bni_std | family + birth_order + byear,  data = sibs)

bni.df <- tidy(bni.all.sibs)

results[[year]] <- bni.df %>% 
  mutate(start_year = year)

cat("Finished with ", year, "-" , year + 9, "\n")
}

results_df <- bind_rows(results)

bcohort_10yr_plot <- results_df %>% 
  filter(start_year >= 1905) %>% 
  ggplot() + 
  geom_line(aes(x = start_year, y = estimate)) + 
  geom_point(aes(x = start_year, y = estimate)) +
  geom_errorbar(aes(x = start_year, y = estimate, ymin = estimate - 1.96*std.error, ymax = estimate + 1.96*std.error)) +
  theme_bw(base_size = 20) + 
  geom_hline(yintercept  = 0, linetype = "dashed") + 
  labs(x = "Birth Cohorts",
       y = "BNI Coefficient",
       title = "BNI Gradient and Birth Cohort (10-Year Windows)") + 
  scale_x_continuous(
  breaks = c(1900, 1905, 1910, 1915, 1920),
  label = c("1900-1909", "1905-1914", "1910-1919", "1915-1924", "1920-1929"), 
  ) + 
  theme(axis.text.x=element_text(angle=-30, vjust = .3, hjust=.25)) + 
  ylim(-3, 1.3)

ggsave(plot = bcohort_10yr_plot, filename = "../figures/bcohort_sensitivity_10yr.pdf", width = 12, height = 8)

```

```{r}
results <- list()
start_year <- 1900:1920

for (year in start_year) {

sibs <- siblings %>% 
  filter(fname_std_freq > 500) %>% 
  filter(!is.na(bni_std)) %>% 
  filter(byear %in% c(year:(year+14)))  %>% 
  group_by(family) %>% 
  filter(n() %in% 2:5) 

bni.all.sibs = felm(death_age ~ bni_std | family + birth_order + byear,  data = sibs)

bni.df <- tidy(bni.all.sibs)

results[[year]] <- bni.df %>% 
  mutate(start_year = year)

cat("Finished with ", year, "-" ,year+14, "\n")
}

results_df_15_yr <- bind_rows(results)

bcohort_15yr_plot <- results_df_15_yr %>% 
  filter(start_year >= 1905) %>% 
  ggplot() + 
  geom_line(aes(x = start_year, y = estimate)) + 
  geom_point(aes(x = start_year, y = estimate)) +
  geom_errorbar(aes(x = start_year, y = estimate, ymin = estimate - 1.96*std.error, ymax = estimate + 1.96*std.error)) +
  theme_bw(base_size = 20) + 
  geom_hline(yintercept  = 0, linetype = "dashed") + 
  labs(x = "Birth Cohorts",
       y = "BNI Coefficient",
              title = "BNI Gradient and Birth Cohort (15-Year Windows)") + 
  scale_x_continuous(
  breaks = c(1900, 1905, 1910, 1915, 1920),
  label = c("1900-1914", "1905-1919", "1910-1924", "1915-1929", "1920-1934"), 
  ) + 
  theme(axis.text.x=element_text(angle=-30, vjust = .3, hjust=.25))+ 
  ylim(-3, 1)

ggsave(plot = bcohort_15yr_plot, filename = "../figures/bcohort_sensitivity_15yr.pdf", width = 12, height = 8)
```

## Concrete Examples of Matching

```{r}
## create table of matches 
knitr::kable(siblings %>% 
  filter(family %in% sample(unique(family), 3)) %>% 
  select(fname_std, lname, father_fname_clean, father_lname_clean, mother_fname_clean, mother_lname_clean, bpl_string) %>% 
  mutate(across(where(is.character), tolower)) %>% 
  mutate(across(where(is.character), tools::toTitleCase)),
  format = "latex", booktabs = T)  

## create table of matches 
knitr::kable(siblings %>% 
  filter(lev_distance_father > 0) %>% 
  filter(family %in% sample(unique(new_sibs_father$family), 3)) %>% 
  select(fname_std, lname, bpl_string, father_fname_clean, father_lname_clean, mother_fname_clean, mother_lname_clean, lev_distance_father) %>% 
  mutate(across(where(is.character), tolower)) %>% 
  mutate(across(where(is.character), tools::toTitleCase)),
  format = "latex", booktabs = T)  
```
```

