---
title: "Models for Presentation"
---

Summary: In this notebook, I calculate the BNI gradient for by race and geography for the birth cohorts of

```{r}
library(data.table) ## for working with big data
library(lfe) ## for fixed effects (with lots of FEs)
library(stargazer) ## for regression output tables
library(tidyverse) ## data manipulation and data viz 
library(broom) ## extract regression output
```


```{r}
## dt fc-server 
dt <- fread("/censoc/data/working_files/bunmd_sib_data.csv")

## read in master nickname file (cleaned)
nicknames_master <- fread("../../data/nickname_crosswalk_master.csv") %>%
  mutate(nickname_master = 1) %>% 
  rename(fname_std_master = fname_std)

## join onto dt 
dt <- merge(dt, nicknames_master, all.x = T, by = c("sex", "fname"))
dt[is.na(nickname_master), nickname_master := 0]
dt[is.na(fname_std_master), fname_std_master := fname]

bni_root <- read_csv("../../data/bni_root_master.csv") %>% 
  rename(bni_root_master = bni_root, n_fname_root_master = n_fname_root)

dt <- left_join(dt, bni_root, by = c("fname_std_master" = "fname_std"))
```


```{r}
dt <- dt %>% 
  group_by(key) %>% 
  mutate(n = n())


dt %>% 
  filter(nkey_male %in% 2:5 &
  sex_score_std_strong < 1.3 & 
  byear %in% 1915:1925 &
  race == 2 &
  sex == 1 &
  n_fname_root_master >= 500) %>% 
  filter(!is.na(nickname_source)) %>% 
  group_by(fname, nickname_source, fname_std_master, bni) %>% 
  tally() %>% 
  arrange(desc(n))
```

```{r}
## BNI Gradient Blacks 
blacks <- dt %>% 
  filter(nkey_male %in% 2:5 &
  sex_score_std_strong < 1.3 & 
  byear %in% 1915:1925 &
  race == 2 &
  sex == 1 &
  n_fname_root_master >= 500)

blacks <- blacks[sex == 1, nkey_male := .N, by = key] %>% 
  filter(nkey_male > 1)

m.bni.black = felm(death_age ~ bni_root_master | key + birth_order + as.factor(byear), data = blacks)

m.bni.black.pooled = felm(death_age ~ bni_root_master | birth_order + as.factor(byear), data = blacks)


## number of family fixed effects 
blacks %>% 
  group_by(key) %>% 
  tally() %>% 
  tally()

## 9227

## BNI Gradient: Whites 
whites <- dt %>% 
  filter(nkey_male %in% 2:5 &
  sex_score_std_strong < 1.3 & 
  byear %in% 1915:1925 &
  race == 1 &
  sex == 1 &
  n_fname_root_master >= 500)

whites <- whites[sex == 1, nkey_male := .N, by = key] %>% 
  filter(nkey_male > 1)

m.bni.white <-  felm(death_age ~ bni_root_master | key + birth_order + as.factor(byear), data = whites)

## number of family fixed effects 
whites %>% 
  group_by(key) %>% 
  tally() %>% 
  tally()

## 157659

stargazer(m.bni.black, m.bni.white,
          type = "text", 
           object.names = T)

```


```{r}
## south socstate
south_socstate.vec = c(10, 11, 12, 13, 24, 37, 45, 51, 54, 1, 21, 28, 47, 05, 22, 40, 48)*100
dt[, south_socstate := socstate %in% south_socstate.vec]

## BNI Gradient Blacks 
north <- dt %>% 
  filter(nkey_male %in% 2:5 &
  south_socstate == FALSE &
  sex_score_std_strong < 1.3 & 
  byear %in% 1915:1925 &
  race == 2 &
  sex == 1 &
  n_fname_root_master >= 500)

north <- north[sex == 1, nkey_male := .N, by = key] %>% 
  filter(nkey_male > 1)

m.bni.north = felm(death_age ~ bni_root_master | key + birth_order + as.factor(byear), data = north)

## number of family fixed effects 
north %>% 
  group_by(key) %>% 
  tally() %>% 
  tally()

## N =  2974

## BNI Gradient: Whites 
south <- dt %>% 
  filter(nkey_male %in% 2:5 &
  south_socstate == TRUE &
  sex_score_std_strong < 1.3 & 
  byear %in% 1915:1925 &
  race == 2 &
  sex == 1 &
  n_fname_root_master >= 500)

south <- south[sex == 1, nkey_male := .N, by = key] %>% 
  filter(nkey_male > 1)

m.bni.south <-  felm(death_age ~ bni_root_master | key + birth_order + as.factor(byear), data = south)

## number of family fixed effects 
south %>% 
  group_by(key) %>% 
  tally() %>% 
  tally()

## N = 5,430

## 157659
stargazer(m.bni.south, m.bni.north,
          type = "text", 
           object.names = T)
```


